import type { MetadataRoute } from "next";

/**
 * Home-screen install is an acceptance criterion (TRACKSURE.md §12). Chrome
 * needs name, start_url, display and both a 192 and a 512 icon before it will
 * offer the prompt; iOS reads `apple-touch-icon` from the layout metadata.
 * Icons are generated by `scripts/generate-pwa-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Tracksure Driver",
    short_name: "Tracksure",
    description:
      "Anfani Transport driver app — current trip, journey plan, waybills and complaints",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    categories: ["business", "productivity"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
